version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/project
    
permissions:
  - object: /home/ubuntu/project
    owner: root
    group: root
    mode: 777
    
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
      
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
      
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
